
import React from 'react';
import { Shield, AlertTriangle } from 'lucide-react';

const LegalSection: React.FC = () => {
  return (
    <section className="py-16 bg-cyber-bg-dark/50 border-t border-cyber-border/20">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <div className="mb-10 text-center">
            <div className="inline-flex items-center justify-center px-4 py-1 mb-6 rounded-full bg-cyber-primary/10 border border-cyber-primary/20">
              <Shield className="w-4 h-4 text-cyber-primary mr-2" />
              <span className="text-cyber-primary text-sm font-semibold">Legal Information</span>
            </div>
            
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Disclaimer & Legal Notices
            </h2>
          </div>

          <div className="cyber-card mb-8">
            <div className="flex items-start">
              <AlertTriangle className="w-6 h-6 text-cyber-accent mr-4 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-semibold mb-3">Disclaimer of Liability</h3>
                <p className="text-cyber-muted mb-4">
                  The Algebraic Expression Inventor GPT is provided "as is" without any warranties, expressed or implied. 
                  While we strive for accuracy, the mathematical expressions and solutions generated by this AI tool may contain 
                  errors or inaccuracies. Users should verify all results independently before implementation in any critical application.
                </p>
                <p className="text-cyber-muted">
                  AI Web Tools LLC, its affiliates, and partners shall not be held liable for any damages, losses, or consequences 
                  arising from the use of or reliance upon the information, suggestions, or expressions generated by this tool. 
                  Users assume full responsibility for the implementation and application of any mathematical expressions or solutions provided.
                </p>
              </div>
            </div>
          </div>

          <div className="cyber-card mb-8">
            <div className="flex items-start">
              <AlertTriangle className="w-6 h-6 text-cyber-accent mr-4 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-semibold mb-3">Limitations of AI Technology</h3>
                <p className="text-cyber-muted">
                  This tool utilizes artificial intelligence to generate mathematical expressions and solutions. As with all AI systems, 
                  it may occasionally produce incorrect, incomplete, or misleading results. It is designed to assist human judgment, 
                  not replace it. All output should be carefully reviewed by users with appropriate expertise before application.
                </p>
              </div>
            </div>
          </div>

          <div className="cyber-card">
            <div className="flex items-start">
              <Shield className="w-6 h-6 text-cyber-primary mr-4 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-semibold mb-3">Usage Policy</h3>
                <p className="text-cyber-muted mb-4">
                  By using this tool, you agree to use it responsibly and in compliance with all applicable laws and regulations. 
                  The tool should not be used for illegal, harmful, or unethical purposes. We reserve the right to restrict access 
                  to users who violate these terms.
                </p>
                <p className="text-cyber-muted">
                  For detailed information about how we protect your data and privacy, please refer to our 
                  <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-cyber-primary ml-1 hover:underline">
                    Privacy Policy
                  </a>. 
                  For complete terms and conditions governing the use of this tool, please review our 
                  <a href="https://aiwebtools.ai/terms-of-services" target="_blank" rel="noopener noreferrer" className="text-cyber-primary ml-1 hover:underline">
                    Terms of Service
                  </a>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LegalSection;
